"""add actor_id to notifications

Revision ID: 20306a1d6020
Revises: 78768de15919
Create Date: 2026-03-25 09:58:07.284181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20306a1d6020'
down_revision = '78768de15919'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_notifications_actor_id', 'users', ['actor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint('fk_notifications_actor_id', type_='foreignkey')
        batch_op.drop_column('actor_id')

    # ### end Alembic commands ###
